/**
 * A basic Markov Chain model to predict the next page navigation
 * based on Google Analytics historical paths.
 */
class MarkovNavigationModel {
  constructor() {
    // In a real application, this matrix is generated by an ML build pipeline (e.g., Guess.js)
    // based on anonymized Google Analytics data.
    this.transitionMatrix = {
      '/': { '/dashboard': 0.7, '/about': 0.2, '/login': 0.1 },
      '/dashboard': { '/collab': 0.6, '/analytics': 0.3, '/profile': 0.1 },
      '/collab': { '/analytics': 0.8, '/dashboard': 0.2 },
    };
  }

  /**
   * Predicts the most likely next route.
   * @param {string} currentPath
   * @param {number} threshold - Minimum probability to trigger a prefetch
   * @returns {string|null} The route to prefetch, or null if none meet the threshold
   */
  predictNextRoute(currentPath, threshold = 0.5) {
    const transitions = this.transitionMatrix[currentPath];
    if (!transitions) return null;

    let bestRoute = null;
    let highestProbability = 0;

    for (const [route, probability] of Object.entries(transitions)) {
      if (probability > highestProbability) {
        highestProbability = probability;
        bestRoute = route;
      }
    }

    if (highestProbability >= threshold) {
      return bestRoute;
    }

    return null;
  }
}

export const navigationModel = new MarkovNavigationModel();
