name: GSSOC Auto-Close

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  auto_close:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Close Issue
        if: github.event_name == 'issues'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.number }}
        run: |
          gh issue close "$ISSUE" -R "$GITHUB_REPOSITORY" --comment "Sorry, we are not continuing in GSSOC anymore. You can continue with other projects."

      - name: Close PR
        if: github.event_name == 'pull_request_target'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.number }}
        run: |
          gh pr close "$PR" -R "$GITHUB_REPOSITORY" --comment "Sorry, we are not continuing in GSSOC anymore. You can continue with other projects."
