name: Migration Lint

on:
  pull_request:
    paths:
      - 'prisma/migrations/**'

jobs:
  lint-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 18
      - name: Run Prisma Linter
        run: node scripts/prisma-lint.js
